#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
PROJECT_VER := 1.0.0
IDF_PATH := esp-idf
PROJECT_NAME := esp-mesh-touch-fw
include $(IDF_PATH)/make/project.mk
