#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := esp_peripherals_app
EXTRA_COMPONENT_DIRS += $(PROJECT_PATH)/../../../
EXCLUDE_COMPONENTS := paybox qr ugui
include $(IDF_PATH)/make/project.mk
